### PR TITLE
Add support for testing

### PR DESCRIPTION
**Pull request by paulmolluzzo**
This adds some generalized support for testing with jest. Most of this is snapshot testing, which is not good, but it's something at least. 😅 

There is an issue with the HOC test, and I can't tell if it's the test or the implementation of the HOC. It shows the error like `Warning: Functions are not valid as a React child...` If you figure it out and want me to change something please let me know. If you want to remove the test for now that's fine too.

Also, I didn't run the linter because it's not possible to run the linter. `eslint` is not a dependency for the project and isn't configured. I'm sure there are code style issues lurking.

### CODE REVIEW

**Comment by paulmolluzzo** [comment]
@braposo I’m going to update the HOC test but can’t get time today. Hang tight please! 🙏🙏🙏

**Comment by braposo** [comment]
@paulmolluzzo this is amazing! Thank you so much! We're going to have a look as soon as possible. 

It's been a bit chaotic these past hours with all of the requests from companies waiting to integrate `graphql-css` into their product. This will definitely make it easier to adopt! 

Don't worry about it, if we have time we'll check it for you, thanks again!

**Comment by paulmolluzzo** [comment]
@braposo @davidgomes fixed the HOC test. 💯 

screen shot 2018-03-21 at 11 39 23 am

**Comment by braposo** [comment]
@paulmolluzzo thank you very much for this, sorry but I had to abruptly leave yesterday so couldn't finish my review. This is fantastic!

**Comment by paulmolluzzo** [comment]
@braposo no apology necessary! Happy to contribute! 😀

**Pull request merged**
